:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:queues:
  - default
  - mailers
  - active_storage
  - action_mailbox

:redis:
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %> 