:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
:queues:
  - [default, 1]
  - [mailers, 2]
  - [sync, 3]

:redis:
  :url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/0") %>
  :network_timeout: 5

:logfile: log/sidekiq.log
:verbose: false 